<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the two tables the price calculation reads from.
 */
final class Version20260907120808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create product and coupon tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE coupon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, type VARCHAR(16) NOT NULL, value INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_coupon_code ON coupon (code)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price_in_cents INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE product');
    }
}
