<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the three tables the price calculation reads from.
 */
final class Version20260923204632 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the product, coupon and tax_rate tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE coupon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(32) NOT NULL, type VARCHAR(16) NOT NULL, amount_in_cents INT DEFAULT NULL, percentage NUMERIC(5, 2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_coupon_code ON coupon (code)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, price_in_cents INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tax_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, country VARCHAR(2) NOT NULL, percent NUMERIC(5, 2) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tax_rate_country ON tax_rate (country)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE coupon');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE tax_rate');
    }
}
